#include "nsISupports.idl"
#include "nsIURI.idl"
#include "nsIInterfaceRequestor.idl"
#include "danbooruITagHistoryService.idl"

[scriptable, uuid(af37695d-9d42-4795-88df-d2208816f201)]
interface danbooruIHelperService : nsISupports
{
	readonly attribute danbooruITagHistoryService tagService;

	void contentLoaded(in nsISupports win);

	//void registerBrowser(in nsISupports window);
	//void unregisterBrowser(in nsISupports window);

	void update(in boolean full, in boolean interactive, in nsIInterfaceRequestor listener);
	void cleanup(in boolean interactive, in nsIInterfaceRequestor listener);
	void downloadRelatedTagDB(in boolean interactive, in nsIInterfaceRequestor listener);

	void startUpload(in nsIURI aRealSource, in wstring aSource, in wstring aTags, in wstring aRating, in wstring aDest,
			in nsIURI aLocation, in nsISupports aWind, in boolean aUpdate);
};

