#include "nsISupports.idl"
#include "nsIAutoCompletePopup.idl"

/* Adds a couple properties for the index hack
 */
[scriptable, uuid(c88d1e59-b0f6-4f3d-83d8-4a0b0dd578c1)]
interface danbooruIAutoCompletePopup : nsIAutoCompletePopup
{
	attribute boolean indexHack;
};

