#include "nsISupports.idl"

/* Wraps nsIAutoCompleteController, adding containers for related tags
 */
[scriptable, uuid(e57488df-6b7a-4be8-af54-5b6624c863e7)]
interface danbooruIAutoCompleteController : nsISupports
{
};

