#include "nsIAutoCompleteResult.idl"

/* noscript */
[uuid(dd0be70d-cd67-4aa1-ab4c-bf0b264e0a5b)]
interface nsIAutoCompleteArrayResult : nsIAutoCompleteResult
{
  /**
   * A writer for the readonly attribute 'searchString' which should contain
   * the string that the user typed.
   */
  void setSearchString(in AString aSearchString);

  /**
   * A writer for the readonly attribute 'errorDescription'.
   */
  void setErrorDescription(in AString aErrorDescription);

  /**
   * A writer for the readonly attribute 'defaultIndex' which should contain
   * the index of the list that will be selected by default (normally 0).
   */
  void setDefaultIndex(in long aDefaultIndex);

  /**
   * A writer for the readonly attribute 'searchResult' which should contain
   * one of the constants nsIAutoCompleteResult.RESULT_* indicating the success
   * of the search.
   */
  void setSearchResult(in unsigned short aSearchResult);

	/* Add a row */
	void addRow(in AString str);
};

