/* Default prefs for DanbooruUp */
pref("extensions.danbooruUp.postadduri", "http://danbooru.donmai.us/post/create.xml");
pref("extensions.danbooruUp.postadduri.selected", 0);
pref("extensions.danbooruUp.fileurlsource", false);
pref("extensions.danbooruUp.checkMD5BeforeUpload", true);
pref("extensions.danbooruUp.updateTagsOnDuplicate", true);
pref("extensions.danbooruUp.updateuri", "http://danbooru.donmai.us/tag/index.xml");
pref("extensions.danbooruUp.suppressComponentAlert", false);
pref("extensions.danbooruUp.autocomplete.enabled", true);
pref("extensions.danbooruUp.autocomplete.site.enabled", true);
pref("extensions.danbooruUp.autocomplete.altsearch", false);
pref("extensions.danbooruUp.autocomplete.threaded", true);
pref("extensions.danbooruUp.autocomplete.limit", 100);
pref("extensions.danbooruUp.autocomplete.keephistory", true);
pref("extensions.danbooruUp.autocomplete.update.onstartup", true);
pref("extensions.danbooruUp.autocomplete.update.beforedialog", false);
pref("extensions.danbooruUp.autocomplete.update.afterdialog", true);
pref("extensions.danbooruUp.autocomplete.update.ontimer", false);
pref("extensions.danbooruUp.autocomplete.update.interval", 120);
pref("extensions.danbooruUp.autocomplete.update.lastupdate", 0);
pref("extensions.danbooruUp.tooltipcrop", "default");
pref("extensions.danbooruUp.hashing.md5", true);
pref("extensions.danbooruUp.hashing.sha1", true);
pref("extensions.danbooruUp.tagtype.0", "");
pref("extensions.danbooruUp.tagtype.1", "color: #a00;");
pref("extensions.danbooruUp.tagtype.2", "background: #ddd;");
pref("extensions.danbooruUp.tagtype.3", "color: #a0a;");
pref("extensions.danbooruUp.tagtype.4", "color: #0a0;");
pref("extensions.danbooruUp.tagtype.0.selected", "");
pref("extensions.danbooruUp.tagtype.1.selected", "");
pref("extensions.danbooruUp.tagtype.2.selected", "");
pref("extensions.danbooruUp.tagtype.3.selected", "");
pref("extensions.danbooruUp.tagtype.4.selected", "");
