/* Default prefs for DanbooruUp */
pref("extensions.danbooruUp.postadduri", "http://miezaru.donmai.us/post/create.xml");
pref("extensions.danbooruUp.postadduri.selected", 0);
pref("extensions.danbooruUp.fileurlsource", false);
pref("extensions.danbooruUp.checkMD5BeforeUpload", true);
pref("extensions.danbooruUp.updateuri", "http://miezaru.donmai.us/tag/index.xml");
pref("extensions.danbooruUp.relatedupdateuri", "http://miezaru.donmai.us/sqlite.db.gz");
pref("extensions.danbooruUp.suppressComponentAlert", false);
pref("extensions.danbooruUp.autocomplete.enabled", true);
pref("extensions.danbooruUp.autocomplete.site.enabled", true);
pref("extensions.danbooruUp.autocomplete.update.onstartup", true);
pref("extensions.danbooruUp.autocomplete.update.faststartup", true);
pref("extensions.danbooruUp.autocomplete.update.beforedialog", false);
pref("extensions.danbooruUp.autocomplete.update.afterdialog", true);
pref("extensions.danbooruUp.autocomplete.update.ontimer", false);
pref("extensions.danbooruUp.autocomplete.update.interval", 120);
pref("extensions.danbooruUp.autocomplete.update.lastupdate", 0);
pref("extensions.danbooruUp.tooltipcrop", "default");
pref("extensions.danbooruUp.hashing.md5", true);
pref("extensions.danbooruUp.hashing.sha1", true);
pref("extensions.danbooruUp.tagtype.0", "background: transparent;");
pref("extensions.danbooruUp.tagtype.1", "background: #88f;\n-moz-padding-end: 8px;");
pref("extensions.danbooruUp.tagtype.2", "background: #4f4;\n-moz-padding-end: 8px;");
pref("extensions.danbooruUp.tagtype.3", "background: #ff0;\n-moz-padding-end: 8px;");
pref("extensions.danbooruUp.tagtype.4", "background: #0ff;\n-moz-padding-end: 8px;");
pref("extensions.danbooruUp.tagtype.0.selected", "background: transparent;");
pref("extensions.danbooruUp.tagtype.1.selected", "background: #88f;\ncolor: -moz-Fieldtext !important;\n-moz-padding-end: 8px;");
pref("extensions.danbooruUp.tagtype.2.selected", "background: #4f4;\ncolor: -moz-Fieldtext !important;\n-moz-padding-end: 8px;");
pref("extensions.danbooruUp.tagtype.3.selected", "background: #ff0;\ncolor: -moz-Fieldtext !important;\n-moz-padding-end: 8px;");
pref("extensions.danbooruUp.tagtype.4.selected", "background: #0ff;\ncolor: -moz-Fieldtext !important;\n-moz-padding-end: 8px;");

