DEPTH		= /cygdrive/c/mingw/work/mozilla/obj-i686-pc-cygwin/
topsrcdir	= /cygdrive/c/mingw/work/mozilla
srcdir		= .
VPATH		= .

include $(DEPTH)/config/autoconf.mk

XPIDL_MODULE	= danbooruUpHelper

XPIDLSRCS	= danbooruUpHelper.idl \
		  $(NULL)

EXTRA_COMPONENTS = danbooruUpHelper.js

include $(topsrcdir)/config/rules.mk

